# Generated by Django 3.1.7 on 2021-03-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('mobile', models.IntegerField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Staff', 'Staff'), ('Teacher', 'Teacher')], default='Staff', max_length=255)),
                ('course', models.ManyToManyField(to='courses.Course')),
            ],
        ),
    ]
