# Generated by Django 3.1.7 on 2021-03-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
