# Generated by Django 3.1.7 on 2021-03-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('staffs', '0002_auto_20210325_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='course',
            field=models.ManyToManyField(null=True, to='courses.Course'),
        ),
    ]
