# Generated by Django 3.1.7 on 2021-03-26 02:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='details',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
