# Generated by Django 3.1.7 on 2021-03-26 02:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20210326_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
